// JSON primitives
export { jsonValueSchema, safeParse, safeStringify } from "./json.js";
export type { JsonValue } from "./json.js";

// Shared JSON-text → schema parse helper (REVIEW-S4).
export { parseJsonWithSchema } from "./parse-json-schema.js";
export type { ParseJsonOutcome } from "./parse-json-schema.js";

// Constants & primitives
export {
  LARGE_PAYLOAD_THRESHOLD_BYTES,
  MAX_IMAGE_ATTACHMENTS,
  MAX_IMAGE_DATA_BYTES,
  PROTOCOL_VERSION,
  SCHEMA_VERSION,
  agentIdSchema,
  callIdSchema,
  eventIdSchema,
  frameIdSchema,
  isoDateTimeSchema,
  requestIdSchema,
  runIdSchema,
} from "./constants.js";
export { desktopMenuChannels } from "./desktop-menu.js";
export type { DesktopMenuChannel } from "./desktop-menu.js";
export {
  createFrameValidationTracker,
  FRAME_VALIDATION_FAILURE_THRESHOLD,
  frameDiscriminator,
} from "./ws-frame-validation.js";
export type { FrameValidationTracker } from "./ws-frame-validation.js";
export type {
  AgentId,
  CallId,
  EventId,
  FrameId,
  IsoDateTime,
  RequestId,
  RunId,
} from "./constants.js";

// Models, modes, statuses, sources
export {
  AUTO_MODEL_ID,
  DEFAULT_MODEL_ID,
  formatModelLabel,
  MODEL_LABELS,
  SDK_RUN_TERMINAL_STATUSES,
  agentModeSchema,
  agentStatusSchema,
  executionModeSchema,
  mcpValidationStatusSchema,
  modelIdSchema,
  modelParameterValueSchema,
  modelParameterDefinitionSchema,
  modelVariantSchema,
  unifiedModelIdSchema,
  knownLanguageSchema,
  replaySpeedSchema,
  sdkRunStatusSchema,
  settingSourceSchema,
  usageSourceSchema,
  themeSettingSchema,
} from "./models.js";
export type {
  AgentMode,
  AgentStatus,
  ExecutionMode,
  McpValidationStatus,
  ModelId,
  ModelParameterValue,
  ModelParameterDefinition,
  ModelVariant,
  UnifiedModelId,
  KnownLanguage,
  ReplaySpeed,
  SdkRunStatus,
  SettingSource,
  UsageSource,
  ThemeSetting,
} from "./models.js";

// Pricing helpers
export {
  DEFAULT_PRICING_MICROS,
  PRICING_SETTING_KEYS,
  dollarsPerMillionToMicros,
  microsToDollars,
  modelPricingSchema,
  pricingKeyForModel,
  pricingPerMillionUsdMicrosSchema,
  pricingPromoMultiplierSchema,
  pricingSettingsSchema,
  pricingValueSchemaByKey,
} from "./pricing.js";
export type { ModelPricing, PricingSettingKey, PricingSettings } from "./pricing.js";

export {
  CONTEXT_DANGER_FRACTION,
  CONTEXT_WARN_FRACTION,
  CONTEXT_WINDOW_TOKENS,
  DEFAULT_CONTEXT_WINDOW_TOKENS,
  MAX_OUTPUT_TOKENS,
  SELF_SUMMARY_DROP_RATIO,
  contextBudgetSchema,
  contextWindowForModel,
  deriveContextBudget,
  isSelfSummaryDrop,
} from "./context-budget.js";
export type { ContextBudget } from "./context-budget.js";

// SDK surface
export {
  assistantSdkMessageSchema,
  cloudAgentOptionsSchema,
  mcpServerConfigSchema,
  modelSelectionSchema,
  requestSdkMessageSchema,
  sdkMessageSchema,
  statusSdkMessageSchema,
  subagentModelOverrideSchema,
  subagentModelSchema,
  systemSdkMessageSchema,
  taskSdkMessageSchema,
  textBlockSchema,
  thinkingSdkMessageSchema,
  tokenUsageSchema,
  toolCallSdkMessageSchema,
  toolUseBlockSchema,
  userSdkMessageSchema,
} from "./sdk-surface.js";
export type {
  CloudAgentOptions,
  McpServerConfig,
  ModelSelection,
  SDKMessage,
  SubagentModel,
  SubagentModelOverride,
  TextBlock,
  TokenUsage,
  ToolUseBlock,
} from "./sdk-surface.js";

// Domain (DB row projections + canonical event base)
export {
  agentRowSchema,
  canonicalEventBaseSchema,
  canonicalEventKindSchema,
  eventRowSchema,
  eventSdkTypeSchema,
  mcpServerRowSchema,
  NON_BROADCAST_EVENT_KINDS,
  runInterruptedReasonSchema,
  runRowSchema,
  sdkImageDimensionSchema,
  sdkImageSchema,
  settingRowSchema,
  subagentDefinitionRowSchema,
  workspaceAllowlistRowSchema,
} from "./domain.js";
export type {
  AgentRow,
  CanonicalEventBase,
  CanonicalEventKind,
  EventRow,
  EventSdkType,
  McpServerRow,
  RunInterruptedReason,
  RunRow,
  SdkImage,
  SdkImageDimension,
  SettingRow,
  SubagentDefinitionRow,
  WorkspaceAllowlistRow,
} from "./domain.js";

// WebSocket protocol
export {
  ackFrameSchema,
  approvalFailedFrameSchema,
  approvalResolvedFrameSchema,
  approvalResponseFrameSchema,
  cancelRunFrameSchema,
  clientFrameSchema,
  clientHeartbeatFrameSchema,
  codeEditDetectedFrameSchema,
  codeEditDetectedPayloadSchema,
  codeEditOperationSchema,
  deleteRunFrameSchema,
  errorFrameSchema,
  frameBaseSchema,
  runFinalResultFrameSchema,
  runInterruptedFrameSchema,
  serverFrameSchema,
  serverHeartbeatFrameSchema,
  subagentCompletedFrameSchema,
  subagentLifecyclePayloadSchema,
  subagentSpawnedFrameSchema,
  submitUserInputFrameSchema,
  subscribeRunFrameSchema,
  unsubscribeRunFrameSchema,
  updateSettingsFrameSchema,
  wsErrorCodeSchema,
} from "./ws-protocol.js";
export type { ClientFrame, ServerFrame, WsErrorCode } from "./ws-protocol.js";

// REST contracts
export {
  agentDetailResponseSchema,
  agentSummarySchema,
  apiKeyPresenceResponseSchema,
  createAgentRequestSchema,
  createMcpServerRequestSchema,
  createRunRequestSchema,
  createRunResponseSchema,
  createSubagentRequestSchema,
  createWorkspaceAllowlistRequestSchema,
  csrfTokenResponseSchema,
  errorEnvelopeSchema,
  canonicalTranscriptEventSchema,
  eventEnvelopeSchema,
  eventLargePayloadResponseSchema,
  eventPayloadResponseSchema,
  getRunEventsQuerySchema,
  getRunEventsResponseSchema,
  healthLiveResponseSchema,
  healthReadyResponseSchema,
  healthVersionResponseSchema,
  listAgentsQuerySchema,
  listAgentsResponseSchema,
  listRunsQuerySchema,
  listRunsResponseSchema,
  largePayloadFieldSchema,
  listMcpServersResponseSchema,
  listSubagentsResponseSchema,
  mcpServerRevealResponseSchema,
  mcpServerSummarySchema,
  replaceMcpServerRequestSchema,
  replaceSubagentRequestSchema,
  subagentSummarySchema,
  runSummarySchema,
  setApiKeyRequestSchema,
  settingsSnapshotSchema,
  updateAgentRequestSchema,
  updateMcpServerRequestSchema,
  updatePricingRequestSchema,
  updateSettingsRequestSchema,
  updateSubagentRequestSchema,
  usageBreakdownResponseSchema,
  usageDailyResponseSchema,
  usageDateRangeQuerySchema,
  usageSummaryResponseSchema,
  validateWorkspacePathRequestSchema,
  validateWorkspacePathResponseSchema,
  transcriptResponseSchema,
  pricingFreshnessSchema,
  activeWorkspaceResponseSchema,
  setActiveWorkspaceRequestSchema,
  fileWriteRequestSchema,
  fileWriteResponseSchema,
  gitStatusResponseSchema,
  listWorkspaceFilesQuerySchema,
  listWorkspaceFilesResponseSchema,
  readWorkspaceFileQuerySchema,
  readWorkspaceFileResponseSchema,
  runSearchQuerySchema,
  runSearchResultSchema,
  runPatchSchema,
  subagentListItemSchema,
  subagentListResponseSchema,
  workspaceFileEntrySchema,
} from "./rest-contracts.js";
export type {
  AgentDetailResponse,
  AgentSummary,
  CanonicalTranscriptEvent,
  CreateAgentRequest,
  CreateMcpServerRequest,
  CreateRunRequest,
  CreateRunResponse,
  CreateSubagentRequest,
  CreateWorkspaceAllowlistRequest,
  ErrorEnvelope,
  EventLargePayloadResponse,
  EventPayloadResponse,
  GetRunEventsResponse,
  LargePayloadField,
  ListAgentsQuery,
  ListMcpServersResponse,
  ListRunsQuery,
  ListSubagentsResponse,
  McpServerRevealResponse,
  McpServerSummary,
  ReplaceSubagentRequest,
  SubagentSummary,
  PricingFreshness,
  RunSummary,
  SettingsSnapshot,
  TranscriptResponse,
  UpdateAgentRequest,
  UpdateMcpServerRequest,
  UpdatePricingRequest,
  UpdateSettingsRequest,
  UpdateSubagentRequest,
  UsageBreakdownRow,
  UsageDailyPoint,
  UsageSummary,
  ActiveWorkspaceResponse,
  SetActiveWorkspaceRequest,
  FileWriteRequest,
  FileWriteResponse,
  GitStatusResponse,
  ListWorkspaceFilesQuery,
  ListWorkspaceFilesResponse,
  ReadWorkspaceFileQuery,
  ReadWorkspaceFileResponse,
  RunSearchQuery,
  RunSearchResult,
  RunPatch,
  SubagentListItem,
  SubagentListResponse,
} from "./rest-contracts.js";


// Browser pane protocol (Phase 18): IPC, state/console/network, MCP tools
export {
  accessibilityNodeSchema,
  browserActionEventSchema,
  browserClickInputSchema,
  browserClickOutputSchema,
  browserConsoleMessagesInputSchema,
  browserConsoleMessagesOutputSchema,
  browserEvaluateInputSchema,
  browserEvaluateOutputSchema,
  browserHistoryOutputSchema,
  browserIdSchema,
  browserInvokeRequestSchema,
  browserInvokeResultSchema,
  browserNavigateInputSchema,
  browserNavigateOutputSchema,
  browserNetworkRequestsInputSchema,
  browserNetworkRequestsOutputSchema,
  browserPushEventSchema,
  browserRectSchema,
  browserScreenshotInputSchema,
  browserScreenshotOutputSchema,
  browserSnapshotInputSchema,
  browserSnapshotOutputSchema,
  browserStateSchema,
  browserTypeInputSchema,
  browserTypeOutputSchema,
  browserWaitForInputSchema,
  browserWaitForOutputSchema,
  consoleLevelSchema,
  consoleMessageSchema,
  networkRequestSchema,
  waitConditionSchema,
} from "./browser-protocol.js";
export type {
  AccessibilityNode,
  BrowserActionEvent,
  BrowserId,
  BrowserInvokeRequest,
  BrowserInvokeResult,
  BrowserPushEvent,
  BrowserRect,
  BrowserState,
  ConsoleLevel,
  ConsoleMessage,
  NetworkRequest,
  WaitCondition,
} from "./browser-protocol.js";
// Embedded-terminal wire protocol (separate from the run-event WS protocol).
export {
  MAX_TERMINAL_INPUT_CHARS,
  MAX_TERMINAL_OUTPUT_CHARS,
  MIN_TERMINAL_DIMENSION,
  MAX_TERMINAL_DIMENSION,
  terminalInputFrameSchema,
  terminalResizeFrameSchema,
  terminalClientFrameSchema,
  terminalReadyFrameSchema,
  terminalDataFrameSchema,
  terminalExitFrameSchema,
  terminalErrorFrameSchema,
  terminalServerFrameSchema,
  terminalViewportSchema,
} from "./terminal-protocol.js";
export type {
  TerminalClientFrame,
  TerminalServerFrame,
  TerminalViewport,
} from "./terminal-protocol.js";

// Context intelligence (Phase 20): @-mentions, rules, codebase search
export {
  contextMentionKindSchema,
  contextMentionSchema,
  contextChipSchema,
  contextSearchResultSchema,
  contextResolveRequestSchema,
  contextResolveResponseSchema,
  resolvedMentionSchema,
  ruleScopeSchema,
  projectRuleSchema,
  grepSearchQuerySchema,
  grepSearchResultItemSchema,
  grepSearchResultSchema,
  fileSearchQuerySchema,
  fileSearchResultSchema,
  contextSearchQuerySchema,
  symbolKindSchema,
} from "./context.js";
export type {
  ContextMentionKind,
  ContextMention,
  ContextChip,
  ContextSearchResult,
  ContextResolveRequest,
  ContextResolveResponse,
  ResolvedMention,
  RuleScope,
  ProjectRule,
  GrepSearchQuery,
  GrepSearchResult,
  FileSearchQuery,
  FileSearchResult,
  ContextSearchQuery,
  SymbolKind,
} from "./context.js";

// Enrichment (Phase 22): Docs indexing, Notepads, Terminal AI, Slash commands
export {
  docsSourceStatusSchema,
  docsSourceSchema,
  addDocsSourceRequestSchema,
  docsSearchQuerySchema,
  docsSearchResultItemSchema,
  docsSearchResultSchema,
  notepadSchema,
  notepadSummarySchema,
  createNotepadRequestSchema,
  updateNotepadContentRequestSchema,
  renameNotepadRequestSchema,
  generateCommandRequestSchema,
  generateCommandResponseSchema,
  slashCommandSchema,
  createSlashCommandRequestSchema,
  updateSlashCommandRequestSchema,
  expandCommandRequestSchema,
  expandCommandResponseSchema,
  slashCommandVariableSchema,
} from "./enrichment.js";
export type {
  DocsSourceStatus,
  DocsSource,
  AddDocsSourceRequest,
  DocsSearchQuery,
  DocsSearchResult,
  Notepad,
  NotepadSummary,
  CreateNotepadRequest,
  UpdateNotepadContentRequest,
  RenameNotepadRequest,
  GenerateCommandRequest,
  GenerateCommandResponse,
  SlashCommand,
  CreateSlashCommandRequest,
  UpdateSlashCommandRequest,
  ExpandCommandRequest,
  ExpandCommandResponse,
  SlashCommandVariable,
} from "./enrichment.js";

// Semantic codebase search (Phase 23): vector embeddings + index status
export {
  DEFAULT_SEMANTIC_MIN_SCORE,
  indexStatusStateSchema,
  indexStatusSchema,
  semanticSearchQuerySchema,
  semanticSearchResultItemSchema,
  semanticSearchResultSchema,
  reindexResponseSchema,
} from "./semantic-search.js";
export type {
  IndexStatusState,
  IndexStatus,
  SemanticSearchQuery,
  SemanticSearchResultItem,
  SemanticSearchResult,
  ReindexResponse,
} from "./semantic-search.js";

// Multi-model providers (Phase 23): BYOK provider registry + unified models
export {
  providerKindSchema,
  addableProviderKindSchema,
  PROVIDER_KIND_LABELS,
  modelProviderSummarySchema,
  listProvidersResponseSchema,
  addProviderRequestSchema,
  updateProviderRequestSchema,
  testProviderResponseSchema,
  modelCapabilitiesSchema,
  modelPricingHintSchema,
  unifiedModelSchema,
  listModelsResponseSchema,
} from "./providers.js";
export type {
  ProviderKind,
  AddableProviderKind,
  ModelProviderSummary,
  ListProvidersResponse,
  AddProviderRequest,
  UpdateProviderRequest,
  TestProviderResponse,
  ModelCapabilities,
  ModelPricingHint,
  UnifiedModel,
  ListModelsResponse,
} from "./providers.js";

export {
  CLI_DISPLAY_NAME,
  CLI_DISPLAY_NAME_NARROW,
  CLI_NAME,
  CLI_NAME_ALIAS,
  CURSOR_SDK_CREDIT,
  CURSOR_SDK_DOCS_URL,
  HARNESS_VERSION,
  ORRERY_VERSION,
  PRODUCT_NAME,
  PRODUCT_TAGLINE,
} from "./brand.js";
